language: r

warnings_are_errors: true


r_binary_packages:
  - roxygen2

r_github_packages:
  - jimhester/covr

before_install:
  - cp ./build/DESCRIPTION ./pkg
  - cd ./pkg

after_install:
  - cd ..
  - R -q -f roxygen.R
  - cd ./pkg

after_success:
  - Rscript -e 'covr::codecov()'

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

