language: r

warnings_are_errors: true

r_packages:
  - roxygen2

before_install:
  - cp ./build/DESCRIPTION ./pkg
  - R -q -f roxygen.R
  - cd ./pkg

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

